### ISSUE TITLE
cconf assumes single argement is options

### ISSUE THREAD

**Issue by tjarvstrand** [paulbellamy/cconf#4]
Hi,

Is there a reason for cconf.core/* assuming that a single argument is options rather than config? The way it works now, I can't seem to get the below to work:
```
  (let [config (-> (cconf/argv)
                   (cconf/env))]
...
```
Instead, I have to use this:
```
  (let [config (-> (cconf/argv)
                   (cconf/env {}))]
```
It would make more sense to me if a single argument would be considered to be the base config.

T

**Comment by paulbellamy** [comment]
Agreed. The double-argument was in mostly for consistency with ```cconf/defaults```. In 1.1.0, I've removed the double-argument from functions where it was not needed. (https://github.com/paulbellamy/cconf/commit/9dc9d0761db8d9e501be51c0348374c39fd918c6)

Thanks!
